baseURL = "https://juliusbroomfield.com"
languageCode = "en-us"
title = "Julius Broomfield"

[params]
  email = "broomfieldjuliusr [at] gmail [dot] com"
  github = "https://github.com/juliusbroomfield"
  linkedin = "https://www.linkedin.com/in/juliusbroomfield/"
  googlescholar = "https://scholar.google.com/citations?view_op=list_projects&hl=en&authuser=1&hl=en&user=mXzRbw8AAAAJ&authuser=1"
  twitter = ""
  cv = "/docs/resume.pdf"
